# Generated by Django 6.0.3 on 2026-03-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('average_annual_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('median_monthly_rent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('population', models.IntegerField()),
                ('country', models.CharField(default='England', max_length=50)),
            ],
        ),
    ]
